PC-926 Script all written, needs full import test still

diff --git a/configure-playbook/roles/deploy-helper-scripts/files/pc-full-import b/configure-playbook/roles/deploy-helper-scripts/files/pc-full-import
--- a/configure-playbook/roles/deploy-helper-scripts/files/pc-full-import
+++ b/configure-playbook/roles/deploy-helper-scripts/files/pc-full-import
@@ -133,7 +133,7 @@ parse_flags_max_attempts() {
 }
 
 ### Help examples
-## TODO Add more examples with the new flags
+## TODO make sure $SCRIPT_NAME works after moved to /usr/local/bin
 help_examples_full_import() {
     echo "# Run a full import from the first step"
     echo "./$SCRIPT_NAME  catalog-prod"
@@ -142,6 +142,11 @@ help_examples_full_import() {
 help_examples_resume_import() {
     echo "# Run a full import from the third step with verbose messages"
     echo "./$SCRIPT_NAME  catalog-prod --first-step 3 -vv"
+}
+
+help_examples_partial_import() {
+    echo "# Show the dry run output of a full import from the third step through the ninth step"
+    echo "./$SCRIPT_NAME  catalog-prod --first-step 3 --last-step 9 --dry-run"
 }
 
 help_examples_list() {
@@ -288,87 +293,357 @@ enable_folio_cron() {
 
 ## Clear our the biblio-build Solr collection
 reset_biblio_build() {
+    print_verbose "        -- Locating build container"
+    NODE=$(get_service_node "$ARG_STACK" "catalog_build")
+    EC=$?
+    if [[ $EC -ne 0 ]] || [[ -z $NODE ]]; then
+        print_error "${RED}Failed to get the node that the build container is running on${RESET}. Exit code: $EC. Output: $NODE"
+        return $EC
+    fi
+
+    print_verbose "        -- Reset the biblio-build Solr collecion"
+    run_in_node_service "$NODE" "$ARG_STACK" "catalog_build" \
+        "pc-import-folio --verbose --reset-solr --collection biblio-build"
+
+    print_verbose "        -- Verify that biblio-build is empty"
+    COUNT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/biblio-build/select?indent=true\&q.op=OR\&q=*%3A*&rows=0\&useParams=" | jq -r '.response.numFound')
+    EC=$?
+    if [[ $EC -ne 0 ]] || [[ -z $COUNT ]]; then
+        print_error "${RED}Failed to get the Solr count for biblio-build${RESET}. Exit code: $EC. Output: $COUNT"
+        return $EC
+    fi
+    if [[ "$COUNT" -ne "0" ]]; then
+        print_error "${RED}The biblio-build collection still has records in it!${RESET}. Current count: $COUNT"
+        return 1
+    fi
+    
     return 0
 }
 
 ## Import the FOLIO records on the build container
 import_folio() {
-    # TODO show FOLIO record count on biblio vs biblio-build
+    print_verbose "        -- Run the FOLIO import"
+    NODE=$(get_service_node "$ARG_STACK" "catalog_build")
+    run_in_node_service "$NODE" "$ARG_STACK" "catalog_build" \
+        "pc-import-folio --verbose --collection biblio-build --batch-import"
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to import FOLIO records into biblio-build${RESET}. Exit code: $EC."
+        return $EC
+    fi
+
+    print_verbose "        -- Getting the biblio FOLIO record count"
+    BIBLIO_COUNT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/biblio/select?indent=true\&q.op=OR\&q=id:folio*&rows=0\&useParams=" | jq -r '.response.numFound')
+    if [[ $EC -ne 0 ]] || [[ -z $BIBLIO_COUNT ]]; then
+        print_error "${RED}Failed to get the FOLIO count for biblio${RESET}. Exit code: $EC. Output: $BIBLIO_COUNT"
+        return $EC
+    fi
+    BUILD_COUNT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/biblio-build/select?indent=true\&q.op=OR\&q=id:folio*&rows=0\&useParams=" | jq -r '.response.numFound')
+    EC=$?
+    if [[ $EC -ne 0 ]] || [[ -z $BUILD_COUNT ]]; then
+        print_error "${RED}Failed to get the FOLIO count for biblio-build${RESET}. Exit code: $EC. Output: $BUILD_COUNT"
+        return $EC
+    fi
+
+    print_info "        -- FOLIO records in biblio:       ${GREEN}$BIBLIO_COUNT${RESET}"
+    print_info "        -- FOLIO records in biblio-build: ${GREEN}$BUILD_COUNT${RESET}"
+
     return 0
 }
 
 ## Temporarily disable the HLM cron from harvesting new files
 disable_hlm_cron() {
-    return 0
+    print_verbose "        -- Check to see if the cron needs to be disabled"
+    if [[ -f /mnt/shared/hlm/${ARG_STACK}/disabled ]]; then
+        print_verbose "        -- Already disabled. Nothing to do."
+        return 0
+    fi
+
+    print_verbose "        -- Temporarily disabling the cron container from running HLM harvests/imports while we copy files"
+    touch /mnt/shared/hlm/"${ARG_STACK}"/enabled && mv /mnt/shared/hlm/"${ARG_STACK}"/enabled /mnt/shared/hlm/"${ARG_STACK}"/disabled
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to disable the HLM cron${RESET}. Exit code: $EC. Command: \n" \
+            "mv /mnt/shared/hlm/${ARG_STACK}/enabled /mnt/shared/hlm/${ARG_STACK}/disabled"
+        return $EC
+    fi
+
+    print_warning "${YELLOW}${BOLD}HLM imports are currently disabled for the cron container.${RESET}" \
+            "If this script fails prior to re-enableing it, be sure to manually enable it by running: \n" \
+            "mv /mnt/shared/hlm/${ARG_STACK}/disabled /mnt/shared/hlm/${ARG_STACK}/enabled"
+    return $EC
 }
 
 ## Copy the HLM harvest files to the build container
 copy_hlm_harvest_files() {
-    return 0
+    print_verbose "        -- Copying of the harvest files to the build container"
+    NODE=$(get_service_node "$ARG_STACK" "catalog_build")
+    CMD="cp /mnt/shared/hlm/${ARG_STACK}/current/* /usr/local/vufind/local/harvest/hlm/"
+    print_verbose "$CMD"
+    run_in_node_service "$NODE" "$ARG_STACK" "catalog_build" "$CMD"
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to copy the harvest files${RESET}. Exit code: $EC. Command: \n$CMD"
+        return $EC
+    fi
+    return $EC
 }
 
 ## Re-enable the HLM cron
 enable_hlm_cron() {
-    return 0
+    print_verbose "        -- Check to see if the cron needs to be enabled"
+    if [[ -f /mnt/shared/hlm/${ARG_STACK}/enabled ]]; then
+        print_verbose "        -- Already enabled. Nothing to do."
+        return 0
+    fi
+
+    print_verbose "        -- Enabling the cron container"
+    CMD="touch /mnt/shared/hlm/${ARG_STACK}/disabled && mv /mnt/shared/hlm/${ARG_STACK}/disabled /mnt/shared/hlm/${ARG_STACK}/enabled"
+    ${CMD}
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to enable the HLM cron${RESET}. Exit code: $EC. Command: \n${CMD}"
+        return $EC
+    fi
+
+    return $EC
 }
 
 ## Import the HLM records in the build container
 import_hlm() {
-    # TODO show HLM record count on biblio vs biblio-build
+    print_verbose "        -- Run the HLM import"
+    NODE=$(get_service_node "$ARG_STACK" "catalog_build")
+    run_in_node_service "$NODE" "$ARG_STACK" "catalog_build" \
+        "pc-import-hlm --verbose --import"
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to import HLM records into biblio-build${RESET}. Exit code: $EC."
+        return $EC
+    fi
+
+    print_verbose "        -- Getting the biblio HLM record count"
+    BIBLIO_COUNT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/biblio/select?indent=true\&q.op=OR\&q=id:hlm*&rows=0\&useParams=" | jq -r '.response.numFound')
+    if [[ $EC -ne 0 ]] || [[ -z $BIBLIO_COUNT ]]; then
+        print_error "${RED}Failed to get the HLM count for biblio${RESET}. Exit code: $EC. Output: $BIBLIO_COUNT"
+        return $EC
+    fi
+    BUILD_COUNT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/biblio-build/select?indent=true\&q.op=OR\&q=id:hlm*&rows=0\&useParams=" | jq -r '.response.numFound')
+    EC=$?
+    if [[ $EC -ne 0 ]] || [[ -z $BUILD_COUNT ]]; then
+        print_error "${RED}Failed to get the HLM count for biblio-build${RESET}. Exit code: $EC. Output: $BUILD_COUNT"
+        return $EC
+    fi
+
+    print_info "        -- HLM records in biblio:       ${GREEN}$BIBLIO_COUNT${RESET}"
+    print_info "        -- HLM records in biblio-build: ${GREEN}$BUILD_COUNT${RESET}"
+
     return 0
 }
 
 ## Build the spellcheck indices on biblio-build
 build_spellcheck() {
+    print_verbose "        -- Run the spellcheck indicies rebuild on biblio-build"
+    solrs=(solr1 solr2 solr3)
+    for solr in "${solrs[@]}"; do
+        print_verbose "        -- Building indicies on ${BOLD}${solr}${RESET}"
+        OUTPUT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr1:8983/solr/biblio-build/select?q=*:*\&spellcheck=true\&spellcheck.build=true")
+        EC=$?
+        if [[ $EC -ne 0 ]]; then
+            print_error "${RED}Failed on step 1 of building the indicies${RESET}. Exit code: $EC. Output: $OUTPUT"
+            return $EC
+        fi
+        OUTPUT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr1:8983/solr/biblio-build/select?q=*:*\&spellcheck.dictionary=basicSpell\&spellcheck=true\&spellcheck.build=true")
+        EC=$?
+        if [[ $EC -ne 0 ]]; then
+            print_error "${RED}Failed on step 1 of building the indicies${RESET}. Exit code: $EC. Output: $OUTPUT"
+            return $EC
+        fi
+    done
+    # TODO maybe add file size checking in the future for
+    # /bitnami/solr/server/solr/biblioN/spellShingle
+    # and /bitnami/solr/server/solr/biblioN/spellchecker
     return 0
 }
 
 ## Show collection counts and get user confirmation to continue
 show_collection_counts() {
+    print_verbose "        -- Getting collection counts for user approval"
+    
+
+    BIBLIO_COUNT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/biblio/select?indent=true\&q.op=OR\&q=id:*&rows=0\&useParams=" | jq -r '.response.numFound')
+    if [[ $EC -ne 0 ]] || [[ -z $BIBLIO_COUNT ]]; then
+        print_error "${RED}Failed to get the record count for biblio${RESET}. Exit code: $EC. Output: $BIBLIO_COUNT"
+        return $EC
+    fi
+    BUILD_COUNT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/biblio-build/select?indent=true\&q.op=OR\&q=id:*&rows=0\&useParams=" | jq -r '.response.numFound')
+    EC=$?
+    if [[ $EC -ne 0 ]] || [[ -z $BUILD_COUNT ]]; then
+        print_error "${RED}Failed to get the record count for biblio-build${RESET}. Exit code: $EC. Output: $BUILD_COUNT"
+        return $EC
+    fi
+
+    print_info "        -- Records in biblio:       ${GREEN}$BIBLIO_COUNT${RESET}"
+    print_info "        -- Records in biblio-build: ${GREEN}$BUILD_COUNT${RESET}"
+
+    # Get user confirmation
+    if [[ $ARG_YES -eq 0 ]]; then
+        read -p "Based on these counts, do you want to continue and do the remaining steps? [Y/n] " -n 1 -r
+        echo ""
+        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+            print_error "Stopping processing"
+            return 1
+        fi
+    fi
+
     return 0
 }
 
 ## Deploy compose file with increased memory allocation required for
 ## doing a collection swap
 increase_solr_memory() {
+    print_verbose "        -- Deploying Solring with higher memory"
+    sudo -Hu deploy bash -c "docker stack deploy --with-registry-auth -c <(source \"/home/deploy/$ARG_STACK/.env\"; envsubst < \"/home/deploy/$ARG_STACK/docker-compose.solr-cloud.yml\") -c <(source \"/home/deploy/$ARG_STACK/.env\"; envsubst < \"/home/deploy/$ARG_STACK/docker-compose.solr-cloud-highmem.yml\") \"$ARG_STACK-solr\""
     return 0
 }
 
 ## Wait for Solr service to update
 wait_for_solr_update() {
-    return 0
+    print_verbose "         -- Waiting for the Solr service to update"
+    ATTEMPTS=1
+
+    print_verbose "(Attempt $ATTEMPTS/$ARG_MAX_ATTEMPTS) Attempting to check the update status of the Solr service"
+    while (( ATTEMPTS <= ARG_MAX_ATTEMPTS )); do
+        STATUS=$(run_on_node 1 "docker service inspect $ARG_STACK-solr_solr --format='{{.UpdateStatus.State}}'")
+        EC=$?
+        # Ignore template parse error because that means the stack was not updated recently and is not in the service
+        # info anymore
+        if [[ "$STATUS" == "completed" ]] || [[ "$STATUS" == *"template parsing error"* ]]; then
+            print_info "(Attempt $ATTEMPTS/$MAX_ATTEMPTS) Stack successfully updated"
+            return 0
+        elif [[ $EC -ne 0 ]]; then
+            print_error "(Attempt $ATTEMPTS/$MAX_ATTEMPTS) Failed to run command on all hosts. Exit Code: $EC. Output: $STATUS"
+        fi
+        # Wait before retrying
+        sleep 1
+        ((ATTEMPTS++))
+    done
+
+    # If we reached this point, then we've gone past the max attempts
+    return 1
 }
 
 ## Perform the collection swap
 solr_collection_swap() {
-    # Get the aliases currently to determine what to swap
-    # curl -s "http://solr:8983/solr/admin/collections?action=LISTALIASES" | grep biblio
+    print_verbose "         -- Performing the collection swap in Solr"
+    
+    print_verbose "         -- Determining what collections to swap based on current alias"
+    BIBLIO=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/admin/collections?action=LISTALIASES" | jq -r '.aliases.biblio')
+    EC=$?
+    if [[ $EC -ne 0 ]] || [[ -z $BIBLIO ]]; then
+        print_error "${RED}Failed to get the alias for biblo${RESET}. Exit code: $EC. Output: $BIBLIO"
+        return $EC
+    fi
+    BUILD=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/admin/collections?action=LISTALIASES" | jq -r '.aliases."biblio-build"')
+    EC=$?
+    if [[ $EC -ne 0 ]] || [[ -z $BIBLIO ]]; then
+        print_error "${RED}Failed to get the alias for biblo-build${RESET}. Exit code: $EC. Output: $BUILD"
+        return $EC
+    fi
+
+    print_verbose "         -- Current: biblio: $BIBLIO. build: $BUILD"
+    print_verbose "         -- Target: biblio: $BUILD. build: $BIBLIO"
+
+    # Perform the swap
+    OUTPUT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/admin/collections?action=CREATEALIAS\&name=biblio-build\&collections=$BIBLIO")
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to swap biblio-build to $BIBLIO${RESET}. Exit code: $EC. Output: $OUTPUT"
+        return $EC
+    fi
+    OUTPUT=$(run_curl_in_local_service "$ARG_STACK" solr_solr "http://solr:8983/solr/admin/collections?action=CREATEALIAS\&name=biblio\&collections=$BUILD")
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to swap biblio to $BUILD${RESET}. Exit code: $EC. Output: $OUTPUT"
+        return $EC
+    fi
+
     return 0
 }
 
 ## Set back the time on the last_harvest file
 reset_last_harvest() {
-    return 0
-}
+    print_verbose "         -- Update the last_harvest file with the time we saved earlier in the process"
 
-## Clear out the old collection, now in biblio-build, asking for user confirmation
-clear_out_biblio_build() {
+    if [[ ! -f "/mnt/shared/oai/${ARG_STACK}/harvest_folio_build/new_last_harvest.txt" ]]; then
+        print_error "${RED}No new harvest time file found to use!${RESET} Path: /mnt/shared/oai/${ARG_STACK}/harvest_folio_build/new_last_harvest.txt"
+        return 1
+    fi
+
+    CMD="mv /mnt/shared/oai/${ARG_STACK}/harvest_folio/last_harvest.txt /mnt/shared/oai/${ARG_STACK}/harvest_folio/last_harvest.txt.backup"
+    ${CMD}
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to make a backup of the last_harvest file${RESET}. Exit code: $EC. Command: \n$CMD"
+        return $EC
+    fi
+
+    CMD="mv /mnt/shared/oai/${ARG_STACK}/harvest_folio_build/new_last_harvest.txt /mnt/shared/oai/${ARG_STACK}/harvest_folio/last_harvest.txt"
+    ${CMD}
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to restore the new last_harvest file${RESET}. Exit code: $EC. Command: \n$CMD"
+        return $EC
+    fi
     return 0
 }
 
 ## Redeploy Solr with the original memory
 reset_solr_memory() {
+    print_verbose "        -- Deploying Solring with original memory settings"
+    sudo -Hu deploy bash -c "docker stack deploy --with-registry-auth -c <(source \"/home/deploy/$ARG_STACK/.env\"; envsubst < \"/home/deploy/$ARG_STACK/docker-compose.solr-cloud.yml\") \"$ARG_STACK-solr\""
     return 0
 }
 
 ## Run the alphabrowse rebuild
 alphabrowse_rebuild() {
+    # TODO haven't run this to test yet
+    # Determine which node is allowed to do the build (per logic in check_skip of alpha-browse.sh)
+    NODE_ORDER=(1 2 3)
+    if [[ "$ARG_STACK" == "catalog-beta" ]]; then
+        NODE_ORDER=(2 1 3)
+    elif [[ "$ARG_STACK" == "catalog-preview" ]]; then
+        NODE_ORDER=(3 1 2)
+    fi
+
+    # Kick off the build
+    CMD="/alpha-browse.sh -v -p /mnt/shared/alpha-browse/${ARG_STACK} -f"
+    run_in_node_service "${NODE_ORDER[0]}" "$ARG_STACK" "solr_cron" "$CMD"
+    EC=$?
+    if [[ $EC -ne 0 ]]; then
+        print_error "${RED}Failed to build the new alphabrowse databases on node ${NODE_ORDER[0]}${RESET}. Exit code: $EC."
+        return $EC
+    fi
+
+    # Do the copy on the remaining nodes
+    for COPY_NODE in "${NODE_ORDER[@]:1}"; do
+        CMD="/alpha-browse.sh -v -p /mnt/shared/alpha-browse/${ARG_STACK}"
+        run_in_node_service "${COPY_NODE}" "$ARG_STACK" "solr_cron" "$CMD"
+        EC=$?
+        if [[ $EC -ne 0 ]]; then
+            print_error "${RED}Failed to copy the new alphabrowse databases on node ${COPY_NODE}${RESET}. Exit code: $EC."
+            return $EC
+        fi
+    done
+
     return 0
 }
 
 ## Run the script to add generated call numbers from solr_solr
 add_generated_call_numbers() {
-    return 0
+    print_verbose "         -- Adding the generated call numbers to Solr"
+    CMD="python3 ./add_generated_call_numbers.py"
+    run_in_node_service 1 "$ARG_STACK" "solr_solr" "python3 ./add_generated_call_numbers.py"
+    return $?
 }
 
 ## List all of the steps used in this script for a full import.
@@ -430,7 +705,7 @@ pc_hook_full_import() {
             continue
         fi
         START_TIME=$(date +%s)
-        ${STEP_FUNCS[$key]}when expan
+        ${STEP_FUNCS[$key]}
         RC=$?
         END_TIME=$(date +%s)
         RUNTIME=$((END_TIME-START_TIME))
@@ -496,7 +771,7 @@ validate_step_params() {
     fi
 
     # Validate that the steps are one of the valid steps
-    if [[ -n $ARG_LAST_STEP ]] && [[ $ARG_LAST_STEP -ge ${#STEPS[@]} ]]; then
+    if [[ -n $ARG_LAST_STEP ]] && [[ $ARG_LAST_STEP -gt ${#STEPS[@]} ]]; then
         die "--last-step must be a step less than or equal to ${#STEPS[@]}. See --list to view all steps"
     fi
     if [[ -n $ARG_FIRST_STEP ]] && [[ $ARG_FIRST_STEP -lt 1 ]]; then
