PC-1150 Add back missing code removed in last commit

diff --git a/configure-playbook/roles/deploy-helper-scripts/files/pc-mount-logs b/configure-playbook/roles/deploy-helper-scripts/files/pc-mount-logs
--- a/configure-playbook/roles/deploy-helper-scripts/files/pc-mount-logs
+++ b/configure-playbook/roles/deploy-helper-scripts/files/pc-mount-logs
@@ -12,6 +12,7 @@ default_args() {
     ARGS[REMOVE]=0
     ARGS[DRYRUN]=0
     ARGS[VERBOSE]=0
+    ARGS[SERVICE]=0
     ARGS[DEBUG]=0
 }
 default_args
@@ -101,6 +102,9 @@ parse_args() {
         -r|--remove)
             ARGS[REMOVE]=1
             shift;;
+        -s|--create-service)
+            ARGS[SERVICE]=1
+            shift;;
         *)
             case "${POSITION}" in
             0)
@@ -135,9 +139,27 @@ catch_invalid_args() {
         && die "TARGET_DIR is a required arugment"
 }
 
+# Mount the volume
 create_mount() {
+    # Remove the mount first, to avoid duplicate mount points
+    remove_mount
+
+    # Create the new mount
+    CMD="mkdir -p ${ARGS[TARGET_DIR]}/${ARGS[STACK_NAME]}/logs &&
+    mount --bind -o ro ${ARGS[SOURCE_DIR]}/_data/ ${ARGS[TARGET_DIR]}/${ARGS[STACK_NAME]}/logs/"
+    verbose "Command:  bash -c '$CMD'"
+    if [[ ${ARGS[DRYRUN]} -eq 0 ]]; then
+        if ! OUTPUT=$(bash -c "$CMD"); then
+            die "Failed to mount into shared dir. ${OUTPUT}"
+        fi
+    fi
+
+}
+
+# Create a systemd service and timer to mount on reboot
+create_service() {
     # Create the service unit and timer to remount on restart
-    CMD="mkdir -p ${ARGS[UNIT_DIR]} && 
+    CMD="mkdir -p ${ARGS[UNIT_DIR]} &&
     sudo mkdir -p ${ARGS[SHARED_DIR]}/local/${ARGS[STACK_NAME]}/deploy/mounts"
     verbose "Command:  bash -c '$CMD'"
     if [[ ${ARGS[DRYRUN]} -eq 0 ]]; then
@@ -188,6 +210,8 @@ EOT
         fi
     fi
 }
+
+# Unmount the log dir
 remove_mount() {
     CMD="umount ${ARGS[TARGET_DIR]}/${ARGS[STACK_NAME]}/logs/ &&
     rmdir ${ARGS[TARGET_DIR]}/${ARGS[STACK_NAME]}/logs/ &&
@@ -195,6 +219,8 @@ remove_mount() {
     verbose "Command:  bash -c '$CMD'"
     ([[ ${ARGS[DRYRUN]} -eq 0 ]] && sh -c "$CMD") || true
 }
+
+# Remove the systemd service and timer
 remove_service() {
     # Check if the services exist, and if so, remove them
     if systemctl list-units --full -all | grep -q "${ARGS[STACK_NAME]}.service"; then
@@ -225,8 +251,15 @@ main() {
             die "Failed to service for volume mount. ${OUTPUT}"
         fi
     else
-        if ! OUTPUT=$(create_mount); then
-            die "Failed to create log volume mount. ${OUTPUT}"
+
+        if [[ ${ARGS[SERVICE]} -eq 1 ]]; then
+            if ! OUTPUT=$(create_service); then
+                die "Failed to create service for log volume mount. ${OUTPUT}"
+            fi
+        else
+            if ! OUTPUT=$(create_mount); then
+                die "Failed to create log volume mount. ${OUTPUT}"
+            fi
         fi
     fi
     # Show output of the deploy command if verbose enabled
